services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


  influxdb:
    image: influxdb:2
    container_name: influxdb

    ports:
      - "8086:8086"

    volumes:
      - influxdb-data:/var/lib/influxdb2


  telegraf:
    image: telegraf:latest
    container_name: telegraf

    depends_on:
      - mosquitto
      - influxdb

    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf


  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana


volumes:

  influxdb-data:
  grafana-data:
