###############################################################################
# AGENT
###############################################################################

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

###############################################################################
# MQTT INPUT
###############################################################################

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  topics = [
    "coffee/telemetry"
  ]

  qos = 0
  connection_timeout = "30s"

  data_format = "json"

###############################################################################
# INFLUXDB OUTPUT
###############################################################################

[[outputs.influxdb_v2]]

  urls = ["http://influxdb:8086"]

  token = "aebXDTF9AfUqmNPqUlvp7jJbHhqbdLSktaagLmGrNg3l56Y2kxEgy2YGeXcga2zHnkQwlXu9NXKaidY9zLqF9A=="

  organization = "felfel"

  bucket = "iot"
